name: venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38h50d1736_1002
  - argon2-cffi=20.1.0=py38h7e3306e_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h94c058a_1001
  - ca-certificates=2020.10.14=0
  - certifi=2020.11.8=py38hecd8cb5_0
  - cffi=1.14.3=py38h2125817_2
  - chardet=3.0.4=py38h5347e94_1008
  - cryptography=3.2.1=py38h5c1d3f9_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - fastcache=1.1.0=py38h1de35cc_0
  - freetype=2.10.4=ha233b18_0
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py38h6ef4df4_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py38h9bb44b7_1
  - ipython=7.19.0=py38h9bb44b7_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.2=py38h50d1736_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38h50d1736_2
  - jupyterlab=2.2.9=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.3.0=py38h23ab428_0
  - lcms2=2.11=h92f6f08_0
  - libblas=3.9.0=1_h508aa58_netlib
  - libcblas=3.9.0=3_h16b37ef_netlib
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=h7cc5361_13
  - libgfortran5=9.3.0=h7cc5361_13
  - liblapack=3.9.0=3_h16b37ef_netlib
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.17=h01d97ff_0
  - libtiff=4.1.0=hcb84e12_1
  - libuv=1.40.0=haf1e3a3_0
  - llvm-openmp=11.0.0=h73239a0_1
  - lz4-c=1.9.2=h79c402e_3
  - markupsafe=1.1.1=py38h94c058a_2
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h181983e_0
  - mistune=0.8.4=py38h7e3306e_1002
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.2.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.1.0=py38_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.1=py38h879752b_0
  - notebook=6.1.5=py38h50d1736_0
  - numpy=1.19.2=py38h456fd55_0
  - numpy-base=1.19.2=py38hcfb5961_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.11.1.1=hbcb3906_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py38h5270095_0
  - pip=20.2.4=py38hecd8cb5_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.2=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h7e3306e_1
  - pysocks=1.7.1=py38h5347e94_2
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.0=py3.8_0
  - pyzmq=19.0.1=py38h1fcdcd6_0
  - readline=8.0=h1de35cc_0
  - requests=2.25.0=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.1=py38hecd8cb5_1
  - six=1.15.0=py38hecd8cb5_0
  - slycot=0.4.0.0=py38h56a78b7_4
  - sqlite=3.33.0=hffcf06c_0
  - sympy=1.6.2=py38hecd8cb5_1
  - terminado=0.9.1=py38h50d1736_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - torchvision=0.8.1=py38_cpu
  - tornado=6.1=py38h7e3306e_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - captum==0.3.0
    - cloudpickle==1.6.0
    - control==0.8.3
    - dataclasses==0.6
    - future==0.18.2
    - gym==0.17.3
    - pyglet==1.5.0
    - scipy==1.5.4
